version: "3.9"
services:
  weatherapp:
    image: weather:latest
    ports:
      - "8081:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "Weather"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12314"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"