version: "3.9"
services:
  weatherapp:
    build:
      context: .
      target: production
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "Weather"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12314"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"