spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: 1234
  session:
    jdbc:
      table-name: spring_session
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/Weather
    username: postgres
    password: 12314
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    session:
      timeout: 30m